-- Systemized Health: Analytics Database Schema Extension for Supabase
-- Run this script in your Supabase SQL Editor to enable channel_monthly_stats and eom_reports tables.

CREATE TABLE IF NOT EXISTS public.channel_monthly_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_month TEXT UNIQUE NOT NULL,
    total_videos INT DEFAULT 0,
    long_videos_count INT DEFAULT 0,
    short_videos_count INT DEFAULT 0,
    total_views INT DEFAULT 0,
    total_subscribers INT DEFAULT 0,
    subscribers_gained INT DEFAULT 0,
    total_likes INT DEFAULT 0,
    total_comments INT DEFAULT 0,
    total_watch_hours FLOAT DEFAULT 0.0,
    avg_ctr_pct FLOAT DEFAULT 0.0,
    avg_vph FLOAT DEFAULT 0.0,
    discovery_call_leads INT DEFAULT 0,
    intensives_converted INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.eom_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_month TEXT UNIQUE NOT NULL,
    report_title TEXT NOT NULL,
    summary_json JSONB,
    markdown_path TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS (Row Level Security) and public read/service role access
ALTER TABLE public.channel_monthly_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.eom_reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow service role full access on channel_monthly_stats" ON public.channel_monthly_stats FOR ALL USING (true);
CREATE POLICY "Allow service role full access on eom_reports" ON public.eom_reports FOR ALL USING (true);
